services:
  web:
    build: .
    # command: gunicorn --workers 3 --bind 0.0.0.0:8000 onebox.wsgi:application
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      # - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  postgres_data:
  # static_volume:
