# Generated by Django 5.0.6 on 2024-06-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContatto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etichetta', models.CharField(max_length=100)),
                ('attivatore', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecapito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etichetta', models.CharField(max_length=100)),
                ('icona', models.CharField(blank=True, max_length=100, null=True)),
                ('colore', models.CharField(blank=True, max_length=100, null=True)),
                ('attivatore', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
