# Generated by Django 5.0.6 on 2024-06-26 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrica', '0002_popola_tipologie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragione_sociale', models.CharField(max_length=255)),
                ('abbreviazione', models.CharField(blank=True, max_length=50, null=True)),
                ('partita_iva', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='La partita IVA deve essere nel formato IT00000000000', regex='^IT[0-9]{11}$')])),
                ('codice_fiscale', models.CharField(blank=True, max_length=16, null=True)),
                ('indirizzo_pec', models.EmailField(blank=True, max_length=254, null=True)),
                ('codice_sdi', models.CharField(blank=True, max_length=7, null=True)),
                ('attivo', models.BooleanField(default=True)),
                ('bloccato', models.BooleanField(default=False)),
                ('sedeMain_riferimento', models.CharField(blank=True, max_length=255, null=True)),
                ('sedeMain_indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('sedeMain_numero_civico', models.CharField(blank=True, max_length=10, null=True)),
                ('sedeMain_cap', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Il CAP deve essere di 5 cifre', regex='^[0-9]{5}$')])),
                ('sedeMain_citta', models.CharField(blank=True, max_length=100, null=True)),
                ('sedeMain_provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('sedeMain_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('sedeMain_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sedeMain_info_mittente', models.CharField(blank=True, max_length=255, null=True)),
                ('sedeMain_info_edificio', models.CharField(blank=True, max_length=255, null=True)),
                ('sedeLegal_indirizzo', models.CharField(blank=True, max_length=255, null=True)),
                ('sedeLegal_numero_civico', models.CharField(blank=True, max_length=10, null=True)),
                ('sedeLegal_cap', models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.RegexValidator(message='Il CAP deve essere di 5 cifre', regex='^[0-9]{5}$')])),
                ('sedeLegal_citta', models.CharField(blank=True, max_length=100, null=True)),
                ('sedeLegal_provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('sedeLegal_telefono_principale', models.CharField(blank=True, max_length=20, null=True)),
                ('sedeLegal_email_principale', models.EmailField(blank=True, max_length=254, null=True)),
                ('sedeLegal_info_mittente', models.CharField(blank=True, max_length=255, null=True)),
                ('sedeLegal_info_edificio', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_contatto', models.ManyToManyField(blank=True, to='rubrica.tipocontatto')),
            ],
        ),
    ]
