# Generated by Django 5.0.6 on 2024-06-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrica', '0003_azienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azienda',
            name='attivo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='bloccato',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
