# Generated by Django 5.0.6 on 2024-06-26 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rubrica', '0004_alter_azienda_attivo_alter_azienda_bloccato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azienda',
            name='partita_iva',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='sedeLegal_cap',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='azienda',
            name='sedeMain_cap',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
